theme: jekyll-theme-minimal
title: Frequant
description: Institutional grade platform for investment research.
logo: https://github.com/frequant/frequant/raw/main/logo.png
show_downloads: false
# google_analytics: [Your Google Analytics tracking ID]
